# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ClickWiki
email: hello@clickwiki.net
description: >- # this means to ignore newlines until "baseurl:"
  A community-driven wiki-based website to archive and
  inform of all things Clickteam, Multimedia Fusion and their
  products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://clickwiki.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ClickWiki
github_username:  ClickWiki
accent_colour: "#0084EB"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Social Links
facebook_url: "https://facebook.com/ClickWiki"
twitter_url: "https://twitter.com/ClickWiki"
github_url: "https://github.com/ClickWiki"
discord_url: "https://discord.gg/42jVPPd"

# Header items
navigation_categories:
    - heading: "All About Clickteam"

    - label: "Clickteam"
      icon: "clickteam.png"
      url: "/404"

    - label: "Products"
      icon: "products.png"
      url: "/404"

    - heading: "Fusion"

    - label: "Exporters"
      icon: "exporters.png"
      url: "/404"

    - label: "Extensions"
      icon: "extensions.png"
      url: "/404"

    - label: "Community Resources"
      icon: "community.png"
      url: "/404"

    - label: "Help & Guidance"
      icon: "help.png"
      url: "/404"

    - label: "Interface"
      icon: "interface.png"
      url: "/404"

    - heading: "Advanced"

    - label: "File Extensions"
      icon: "extensions.png"
      url: "/404"

    - label: "Chowdren"
      icon: "chowdren.png"
      url: "/404"

navigation_external_links:
    - label: "Clickteam"
      icon: "clickteam.png"
      url: "https://www.clickteam.com"

    - label: "Clickteam Community"
      icon: "community.png"
      url: "https://community.clickteam.com"

    - label: "Community Passport"
      icon: "passport.png"
      url: "http://community.clickteam.com/passport"

    - label: "Clickteam Shop"
      icon: "shop.png"
      url: "http://www.clickteam.com/web-shop"

    - label: "ClickStore"
      icon: "clickstore.png"
      url: "http://clickstore.clickteam.com/"

    - label: "Bug Tracker"
      icon: "bugtracker.png"
      url: "http://bugbox.clickteam.com/"
